### ISSUE TITLE
Problems not solved in week3:

### ISSUE THREAD

**Issue by LIU221** [LIU221/159356_gruop7_ScotlandYard#2]
(1) AI: mrx.py and detectives.py It's just random selection, it doesn't implement real AI
(2) No multiplayer game
(3) Without implementation: detective players can't see the Mrx location
(4) There is no implementation to put the history of Mrx on the GUI
(5) Multi person online is not realized
(6) Not compatible with windows and Linux
(7) We also need to beautify the GUI
(8) The game also needs to be optimized

**Comment by L-Z-M** [comment]
1.The 2x ticket should add a cancel button. If the player touches it by mistake, he can only take two steps, which is not very intelligent

**Comment by LIU221** [comment]
The existence of this issue is unreasonable: too many questions are raised at the same time. So I decided to close this issue and sort out the problems we encountered.
